<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class RedirectController extends Controller
{
    //

    public function redirect_article_en($slug)
    {
        session()->flush();
        session()->put('locale', 'en');
        $articles_list = [
            'degrees-of-comparisson',
            'discoverer-of-america',
            'medical-school',
            'definition-of-present-perfect-tense',
            'ruminant-animals-characteristics-anatomy-and-digestive-system',
            'exploring-geometric-3d-shapes',
            '7-positive-impacts-of-online-learning-that-you-should-know',
            'getting-to-know-the-five-senses',
            'type-of-clouds',
            'definition-of-superlative-degree-form-and-usage',
            'getting-to-know-volcanoes-and-volcanism',
            'how-to-enhance-character-development-in-schools',
            'top-10-essential-life-skills-for-high-school-students',
            '10-steam-activities-for-kids',
            '7-benefits-of-collaborative-learning',
            'online-vs-traditional-education-a-breakdown-of-the-key-differences',
            'what-effect-does-food-have-on-your-growth-and-development',
            'intercultural-communication-definition-goals-and-benefits',
            'newtons-laws-of-motion',
            'online-safety-wellness-5-tips-to-navigate-digital-world',
            'definition-of-capillarity',
            'static-electricity',
            'how-to-implement-design-thinking-in-elementary-schools',
            'sampoerna-academy-celebrates-outstanding-achievements-at-seamo-2023',
            '5-reasons-why-arts-education-is-important-for-students',
            'how-does-photosynthesis-get-started-in-the-morning',
            'socratic-method',
            'greenhouse-effect',
            'gamification-for-learning',
            'character-education-in-early-childhood',
            'online-learning-is-the-future-of-education',
            'extracurriculars-at-sampoerna-academy',
            'engineering-design-process',
            '8-hands-on-home-learning-activities-for-preschool-children',
            'best-education-system',
            'igcse-curriculum-at-sampoerna-academy',
            'how-can-we-recycle-plastic-more-sustainably',
            'world-mathematics-invitational-wmi-2018',
            '7-playful-math-activities-for-preschoolers',
            'types-of-learning-styles',
            'growth-mindset',
            'raising-a-trilingual-child-with-sampoerna-academy',
            'sampoerna-academy-wins-outstanding-cambridge-learner-awards-through-7-of-its-students',
            'sampoerna-academy-students-excel-at-amo-2023',
            'sa-students-admitted-to-top-class-universities',
            'how-high-can-you-count-in-english',
            'fixed-and-growth-mindset',
            'our-u19-team-won-second-place-in-jsf-league-and-greenfields-cup',
            'empowering-global-citizens-through-multicultural-education-at-sampoerna-academy',
            'social-and-emotional-learning',
            'mammals',
            'preparing-for-the-future-stem-vs-steam-education',
            'definition-of-mind-mapping',
            '7-facts-you-need-to-know-about-mangrove-trees',
            'why-steam-is-important',
            'what-effect-does-farming-have-on-air-quality',
            'the-benefits-of-diversity-for-students-in-international-schools',
            'research-skills',
            'personal-benchmarking-a-tool-for-students-to-grow',
            'why-it-is-important-to-understand-your-childs-learning-style',
            'fifty-nine-sa-students-qualify-for-wmi-2018-final-in-seoul',
            'sampoerna-academy-inaugurates-new-school-in-sun-plaza-medan-with-power-of-play-learning-method',
            'bright-future-in-sampoerna-academy',
            'supporting-the-creation-of-young-innovators-sampoerna-academy-once-again-hosts-steam-expo-2024',
            'why-you-need-to-start-saving-for-your-childs-education-early',
            'supporting-literacy-among-students-the-sampoerna-academy-surabaya-library-received-a-grade-a-from-the-national-library-of-indonesia',
            'sampoerna-academy-joins-hand-with-blcu-for-chinese-language-teaching',
            'does-reading-make-you-smarter',
            'the-impacts-of-fast-food-on-your-health-and-skin',
            'how-do-you-calculate-brain-age',
            '7-digital-tools-for-your-mental-health',
            '3-major-changes-when-moving-from-primary-to-secondary-school',
            '5-ideas-for-family-bonding-during-school-holidays',
            '15-signs-of-a-good-preschool-and-early-childhood-programme',
            'students-of-sampoerna-academy-achieved-medals-in-world-scholars-cup-2024-bangkok-global-round',
            'why-is-visual-literacy-important-for-middle-school-students',
            'why-handwriting-practice-good-for-your-brain',
            'international-education',
            'gold-and-silver-acknowledgement-for-sampoerna-academy-medan',
            'the-ultimate-essay-writing-tips-that-you-need-to-know',
            'frequently-asked-question-about-sampoerna-academy-online',
            'raising-childrens-awareness-of-the-earths-sustainability-sampoerna-academy-held-healing-earth-through-arts-hearts-workshop',
            'sampoerna-academy-emphasizes-the-teacher-synergy-parents-and-students-in-children-success-in-virtual-schooling',
            'sampoerna-academy-to-build-a-new-campus-in-surabaya',
            'marvelyn-andersen-get-top-in-the-world-for-chinese-mandarin-cie-2017',
            'the-synergy-of-ai-and-scientific-progress',
            'google-outreach-visited-sampoerna-academy',
            'arfan-won-a-silver-medal-at-ieyi-international-exhibition-for-young-inventors',
            'benefits-of-outdoor-play-for-toddlers',
            'whats-the-right-age-to-start-preschool-education',
            '10-facts-about-the-human-body',
            'why-is-green-chemistry-important-in-sustainable-development',
            'why-is-the-great-barrier-reef-important',
            'fluoride-in-toothpaste-is-it-good-or-bad',
            '8-tips-on-how-to-ace-your-online-exam',
            'game-based-learning',
            'how-are-mosquitoes-related-to-malaria',
            'why-do-we-make-eye-movements-while-reading',
            '8-self-care-tips-for-students-for-preparation-igcse-ib-dp-exams',
            'school-facilities-at-sampoerna-academy',
            'sampoerna-academy-is-ready-to-open-its-second-school-in-surabaya-for-the-2022-academic-year',
            'collaborative-learning',
            'solar-system',
            'tricks-when-studying-online',
            'clarification-statement',
            'empowering-independent-thought-through-inquiry-led-learning',
            'high-quality-teaching-and-learning-in-secondary-school-sa-sentul',
            'the-olfactory-nerve-systems-do-for-you',
            'integrating-language-skills-in-early-childhood',
            'the-new-looks-of-sampoerna-academy-medan-cipto-campus',
            'committed-to-helping-improve-quality-of-education-sampoerna-academy-medan-donates-computer-lab',
            'how-can-we-track-the-life-of-sea-animals',
            'sampoerna-academy-stands-out-with-the-descendant-of-the-dragon-lunar-new-year-celebration',
            'sampoerna-academy-bsd-officially-launched',
            'why-storytelling-is-a-powerful-skill-and-importance-for-students',
            'what-is-el-nino-and-how-do-they-change-the-weather',
            'what-our-bodies-say-about-loud-sounds',
            'what-exactly-is-aquaponics-a-promising-tool-for-eco-friendly-farming',
            'steam-expo-2018-build-create-and-explore-through-steam',
            'campus-in-surabaya',
            'how-do-the-brain-and-memory-grow-up-together',
            'play-based-learning',
            'boost-math-grades-from-d-to-a-sampoerna-academy-guide',
            'top-trends-in-education-for-2023-and-beyond',
            'what-you-should-know-about-dental-caries-and-how-to-prevent-it',
            'second-place-and-black-medal-in-south-east-asian-mathematics-competition-seamc-2018',
            'nutritious-lunch-ideas',
            'sampoerna-academy-medan-students-won-5-gold-medals-trophy-in-the-first-lego-championship',
            'what-is-fructose-and-how-does-it-contribute-to-health-risks',
            'why-enroll-your-child-in-a-preschool-in-indonesia',
            'why-sampoerna-academy-online-is-the-right-choice-for-future',
            'four-sampoerna-academy-students-compete-in-worlds-largest-science-fair-in-the-u-s',
            'sampoerna-academy-surabayas-building-topping-off',
            'obtaining-qualifications-through-online-schooling',
            'the-mindful-integration-of-digital-learning',
            'the-pandemic',
            'timothy-abisha-from-sampoerna-academy-won-silver-medals-in-ieyi-international-event',
            'how-sampoerna-academy-make-math-interesting-and-engaging',
            'local-educator-receives-international-award-in-environmental-learning',
            'the-celebration-of-sampoerna-academy-surabaya',
            'why-choose-the-ibdp-at-sampoerna-academy',
            'becoming-online-parents',
            'intel-galileo-and-arduino-innovation-competition-2016',
            'sampoerna-academy-applies-steam-learning-method-to-keep-the-spirit-high-during-virtual-schooling-at-home',
            'sampoerna-academy',
            '5-reasons-why-ibdp-is-respected-by-worlds-leading-universities',
            'tips-for-nurturing-independence-skills-in-your-child-or-toddler',
            'supporting-numeracy-in-primary-school-sampoerna-academy-bsd',
            'focusing-on-steam-education-sampoerna-academy-prepares-your-childrens-future-in-the-technology-era',
            'how-sampoerna-academy-can-build-resilience-in-young-students',
            'influencing-the-future-of-education-with-sampoerna-academy',
            'what-is-a-dental-plaque-causes-and-removal',
            '5-most-effective-saving-tips-for-students-that-need-to-know',
            '6-reasons-to-choose-sampoerna-academy-online-for-education',
            'memory-loss',
            'involvement-and-participation-of-sa-medan-elc-mentors-in-anps-early-childhood-conference-2018',
            'to-help-students-conquer-stage-fright-sampoerna-acedemy-holds-regular-english-presentation-session',
            'ways-to-cultivate-your-kids-reading-ability-with-sampoerna-academy-medan',
        ];

        // Redirect with 301 status to the desired URL
        if (in_array($slug, $articles_list)) {
            return redirect('/news/' . $slug, 301);
        }

        abort(404);
    }

    public function redirect_article_id($slug)
    {
        session()->flush();
        session()->put('locale', 'id');
        $articles_list = [
            'mengenal-grit-definisi-dan-cara-menerapkannya',
            'apa-itu-psikomotorik',
            'permainan-anak-yang-mendidik',
            'idmengenal-8-jenis-kecerdasan-anak-dan-cara-mengasahnya',
            'tahap-perkembangan-kognitif-anak',
            'kewajiban-anak-di-sekolah',
            'apa-itu-gtm-dan-cara-mengatasinya',
            'ciri-strict-parents-dan-dampaknya',
            'tips-cara-membantu-anak-belajar-membaca',
            'apa-itu-pendidikan-karakter-kenali-fungsi-dan-manfaatnya',
        ];

        // Redirect with 301 status to the desired URL
        if (in_array($slug, $articles_list)) {
            return redirect('/news/' . $slug, 301);
        }

        abort(404);
    }
}
